title: "plc-st-review"
description: "Semantic code review for IEC 61131-3 Structured Text pull requests"
theme: jekyll-theme-cayman
url: "https://HeytalePazguato.github.io"
baseurl: "/plc-st-review"

show_downloads: true
github:
  repository_url: "https://github.com/HeytalePazguato/plc-st-review"

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap

relative_links:
  enabled: true
  collections: true

include:
  - CHANGELOG.md
